In [1]:
import numpy as np

In [2]:
arr_1d = np.array([1, 2, 3, 4, 5])
print(f"1D Array: {arr_1d}")

1D Array: [1 2 3 4 5]


In [3]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(f"2D Array:\n{arr_2d}")

2D Array:
[[1 2 3]
 [4 5 6]]


In [4]:
arr_2d.shape

(2, 3)

In [5]:
zeros = np.zeros((2, 3))
print(f"Zeros Array:\n{zeros}")

Zeros Array:
[[0. 0. 0.]
 [0. 0. 0.]]


In [6]:
ones = np.ones((2, 3))
print(f"Ones Array:\n{ones}")

Ones Array:
[[1. 1. 1.]
 [1. 1. 1.]]


In [7]:
range_arr = np.arange(0, 10, 2)
print(f"Range Array:\n{range_arr}")

Range Array:
[0 2 4 6 8]


In [8]:
range_array = np.arange(1, 20, 2)
print(f"Range Array:\n{range_array}")

Range Array:
[ 1  3  5  7  9 11 13 15 17 19]


In [9]:
arr_sum = arr_1d + 10
print(f"Sum of 1D Array with 10: {arr_sum}")

Sum of 1D Array with 10: [11 12 13 14 15]


In [12]:
# not use numpy
nums = [1, 2, 3, 4, 5]
for i in range(len(nums)):
    nums[i] += 10
print(f"Modified List: {nums}")

Modified List: [11, 12, 13, 14, 15]


In [14]:
[num + 10 for num in nums]

[21, 22, 23, 24, 25]

In [10]:
arr_product = arr_1d * 2
print(f"Product of 1D Array with 2: {arr_product}")

Product of 1D Array with 2: [ 2  4  6  8 10]


In [15]:
arr_2d_product = arr_2d * np.array([1, 2, 3])
print(f"Product of 2D Array with [1, 2, 3]:\n{arr_2d_product}")

Product of 2D Array with [1, 2, 3]:
[[ 1  4  9]
 [ 4 10 18]]


In [16]:
arr_reshape = np.arange(12).reshape(3, 4)
print(f"Reshaped Array:\n{arr_reshape}")

Reshaped Array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [17]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [18]:
arr_reshape.shape

(3, 4)

In [19]:
sqrt_arr = np.sqrt(arr_reshape)
print(f"Square Root of 2D Array:\n{sqrt_arr}")

Square Root of 2D Array:
[[0.         1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974 2.64575131]
 [2.82842712 3.         3.16227766 3.31662479]]


In [21]:
log_arr = np.log1p(arr_reshape)
print(f"Logarithm of 2D Array:\n{log_arr}")

Logarithm of 2D Array:
[[0.         0.69314718 1.09861229 1.38629436]
 [1.60943791 1.79175947 1.94591015 2.07944154]
 [2.19722458 2.30258509 2.39789527 2.48490665]]


In [23]:
arr = np.arange(1, 11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [24]:
mean_val = np.mean(arr)
print(f"Mean of Array: {mean_val}")

Mean of Array: 5.5


In [25]:
np.median(arr)

np.float64(5.5)

In [26]:
np.std(arr)

np.float64(2.8722813232690143)

In [27]:
random_coords = np.random.uniform(low=-90, high=90, size=(10, 2))
print(f"Random Coordinates:\n{random_coords}")

Random Coordinates:
[[ 69.15598765 -49.66740088]
 [ 22.27797458  71.02591774]
 [-82.53961243 -15.2367288 ]
 [-61.23066406  79.27250936]
 [-89.25103203   9.44787361]
 [-48.5917129  -60.52641808]
 [-24.88017275  -9.83542641]
 [ 83.53212374 -56.25314372]
 [ 71.69675047 -80.88471541]
 [-31.34559942 -58.7893485 ]]


In [30]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
first_element = arr[0]
print(f"First Element: {first_element}")
last_element = arr[-1]
print(f"Last Element: {last_element}")

First Element: 1
Last Element: 10


In [32]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
element = arr_2d[1, 2]
print(f"Element at (1, 2): {element}")

Element at (1, 2): 6


In [34]:
element_last = arr_2d[-1, -1]
print(f"Last Element in 2D Array: {element_last}")

Last Element in 2D Array: 9


In [44]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [45]:
# slicing -get multiple elements from the array
arr_slice = arr[2:5]
print(f"Sliced Array from the third element to the fifth element: {arr_slice}")

Sliced Array from the third element to the fifth element: [3 4 5]


In [39]:
arr_slice = arr[2:]
print(f"Sliced Array from the third elements to end: {arr_slice}")

Sliced Array from the third elements to end: [ 3  4  5  6  7  8  9 10]


In [ ]:
arr_slice = arr[:4]
print(f"Sliced Array from the first element to the fourth element: {arr_slice}")

Sliced Array from the first element to the fourth element: [1 2 3 4]


In [41]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [42]:
# Slice the first two rows and all columns
slice_2d = arr_2d[:2, :]
print(f"Sliced 2D array (first two rows):\n{slice_2d}")

Sliced 2D array (first two rows):
[[1 2 3]
 [4 5 6]]


In [43]:
# Slice the last two rows and the first two columns
slice_2d_partial = arr_2d[1:, :2]
print(f"Sliced 2D array (last two rows, first two columns):\n{slice_2d_partial}")

Sliced 2D array (last two rows, first two columns):
[[4 5]
 [7 8]]


In [50]:
arr_2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [51]:
arr_2d[1, 1]

np.int64(5)

In [53]:
arr_2d[2:, :]

array([[7, 8, 9]])

In [54]:
# Create a 1D array
arr = np.array([10, 20, 30, 40, 50])

In [55]:
# Boolean condition to select elements greater than 25
condition = arr > 25
print(f"Boolean condition: {condition}")

Boolean condition: [False False  True  True  True]


In [56]:
arr[condition]

array([30, 40, 50])

In [57]:
arr[arr > 25]

array([30, 40, 50])

In [58]:
arr[arr < 35]

array([10, 20, 30])

In [59]:
arr[arr > arr.mean()]

array([40, 50])

In [60]:
arr[arr > arr.mean() + arr.std()]

array([50])

In [61]:
# Create a 1D array
arr = np.array([10, 20, 30, 40, 50])

# Iterating through the array
for element in arr:
    print(f"Element: {element}")

Element: 10
Element: 20
Element: 30
Element: 40
Element: 50


In [62]:
# Create a 2D array
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Iterating through rows of the 2D array
print("Iterating over rows:")
for row in arr_2d:
    print(row)

# Iterating through each element of the 2D array
print("\nIterating over each element:")
for row in arr_2d:
    for element in row:
        print(element, end=" ")

Iterating over rows:
[1 2 3]
[4 5 6]
[7 8 9]

Iterating over each element:
1 2 3 4 5 6 7 8 9 

In [63]:
nums = [10, 20, 30, 40, 50]

In [65]:
nums[2] = 35
nums

[10, 20, 35, 40, 50]

In [ ]:
arr = np.array([10, 20, 30, 40, 50])

# Modify the element at index 1
arr[1] = 25
print(f"Modified array: {arr}")

Modified array: [10 25 30 40 50]


In [67]:
# Modify multiple elements using slicing
arr[2:4] = [35, 45]
print(f"Modified array with slicing: {arr}")

Modified array with slicing: [10 25 35 45 50]


In [ ]:
# same value applies for several elements
arr[2:4] = [35]
print(f"Modified array with slicing: {arr}")

Modified array with slicing: [10 25 35 35 50]
